import { Course } from "./types";

const coursesData: Course[] = [
  // =====================================================
  // PRIMARY – GRADE 1
  // =====================================================
  {
    id: "primary-g1-math",
    name: "الرياضيات – الصف الأول",
    description: "أساسيات الأرقام والعمليات الحسابية بطريقة مبسطة",
    stage: "primary",
    grade: "grade-1",
    sessionsCount: 24,
    totalHours: 18,
    thumbnail: "../public/photos/aboutUs.jpg",
    isActive: true,
    pricing: { isFree: false, price: 25, currency: "USD" },
  },
  {
    id: "primary-g1-arabic",
    name: "اللغة العربية – الصف الأول",
    description: "تعلم القراءة والكتابة من الصفر",
    stage: "primary",
    grade: "grade-1",
    sessionsCount: 20,
    totalHours: 15,
    thumbnail: "/images/courses/arabic-g1.png",
    isActive: true,
    pricing: { isFree: true, price: 0, currency: "USD" },
  },
  {
    id: "primary-g1-english",
    name: "اللغة الإنجليزية – الصف الأول",
    description: "الحروف والكلمات الأساسية بطريقة ممتعة",
    stage: "primary",
    grade: "grade-1",
    sessionsCount: 18,
    totalHours: 14,
    thumbnail: "/images/courses/english-g1.png",
    isActive: true,
    pricing: { isFree: false, price: 20, currency: "USD" },
  },
  {
    id: "primary-g1-science",
    name: "العلوم – الصف الأول",
    description: "التعرف على الطبيعة والبيئة المحيطة",
    stage: "primary",
    grade: "grade-1",
    sessionsCount: 16,
    totalHours: 12,
    thumbnail: "/images/courses/science-g1.png",
    isActive: true,
    pricing: { isFree: false, price: 18, currency: "USD" },
  },

  // =====================================================
  // PRIMARY – GRADE 2
  // =====================================================
  {
    id: "primary-g2-math",
    name: "الرياضيات – الصف الثاني",
    description: "الجمع والطرح والضرب بأسلوب تدريجي",
    stage: "primary",
    grade: "grade-2",
    sessionsCount: 26,
    totalHours: 20,
    thumbnail: "/images/courses/math-g2.png",
    isActive: true,
    pricing: { isFree: false, price: 28, currency: "USD" },
  },
  {
    id: "primary-g2-arabic",
    name: "اللغة العربية – الصف الثاني",
    description: "تحسين مهارات القراءة والكتابة",
    stage: "primary",
    grade: "grade-2",
    sessionsCount: 22,
    totalHours: 17,
    thumbnail: "/images/courses/arabic-g2.png",
    isActive: true,
    pricing: { isFree: false, price: 22, currency: "USD" },
  },
  {
    id: "primary-g2-english",
    name: "اللغة الإنجليزية – الصف الثاني",
    description: "جمل بسيطة ومحادثات أساسية",
    stage: "primary",
    grade: "grade-2",
    sessionsCount: 20,
    totalHours: 16,
    thumbnail: "/images/courses/english-g2.png",
    isActive: true,
    pricing: { isFree: false, price: 22, currency: "USD" },
  },
  {
    id: "primary-g2-science",
    name: "العلوم – الصف الثاني",
    description: "اكتشاف العالم من حولنا بأسلوب تفاعلي",
    stage: "primary",
    grade: "grade-2",
    sessionsCount: 22,
    totalHours: 16,
    thumbnail: "/images/courses/science-g2.png",
    isActive: true,
    pricing: { isFree: false, price: 22, currency: "USD" },
  },

  // =====================================================
  // MIDDLE – GRADE 1
  // =====================================================
  {
    id: "middle-g1-math",
    name: "الرياضيات – الصف الإعدادي الأول",
    description: "الجبر والهندسة بأسلوب مبسط",
    stage: "middle",
    grade: "grade-1",
    sessionsCount: 30,
    totalHours: 24,
    thumbnail: "/images/courses/math-middle.png",
    isActive: true,
    pricing: { isFree: false, price: 40, currency: "USD" },
  },
  {
    id: "middle-g1-arabic",
    name: "اللغة العربية – الصف الإعدادي الأول",
    description: "النحو والتعبير والقراءة التحليلية",
    stage: "middle",
    grade: "grade-1",
    sessionsCount: 28,
    totalHours: 22,
    thumbnail: "/images/courses/arabic-middle.png",
    isActive: true,
    pricing: { isFree: false, price: 35, currency: "USD" },
  },
  {
    id: "middle-g1-science",
    name: "العلوم – الصف الإعدادي الأول",
    description: "أساسيات الفيزياء والكيمياء",
    stage: "middle",
    grade: "grade-1",
    sessionsCount: 26,
    totalHours: 21,
    thumbnail: "/images/courses/science-middle.png",
    isActive: true,
    pricing: { isFree: false, price: 38, currency: "USD" },
  },

  // =====================================================
  // SECONDARY – GRADE 2
  // =====================================================
  {
    id: "secondary-physics",
    name: "الفيزياء – المرحلة الثانوية",
    description: "شرح قوانين الفيزياء مع تطبيقات عملية",
    stage: "secondary",
    grade: "grade-2",
    sessionsCount: 40,
    totalHours: 32,
    thumbnail: "/images/courses/physics.png",
    isActive: true,
    pricing: { isFree: false, price: 60, currency: "USD" },
  },
  {
    id: "secondary-math",
    name: "الرياضيات – المرحلة الثانوية",
    description: "التفاضل والتكامل وحل المسائل المتقدمة",
    stage: "secondary",
    grade: "grade-2",
    sessionsCount: 42,
    totalHours: 34,
    thumbnail: "/images/courses/math-secondary.png",
    isActive: true,
    pricing: { isFree: false, price: 55, currency: "USD" },
  },
  {
    id: "secondary-chemistry",
    name: "الكيمياء – المرحلة الثانوية",
    description: "التفاعلات الكيميائية والمعادلات",
    stage: "secondary",
    grade: "grade-2",
    sessionsCount: 38,
    totalHours: 30,
    thumbnail: "/images/courses/chemistry.png",
    isActive: true,
    pricing: { isFree: false, price: 58, currency: "USD" },
  },
];

export default coursesData;
